### ISSUE TITLE
Local Host Credentials

### ISSUE THREAD

**Issue by Sharmajivibhor** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#10]
01-prepare-data-with-power-query-in-power-bi-desktop.md

# Module: 01
#### Step: 03
Task 3: Get data from SQL Server

Description of issue: What type of credentials are to be used 

Repro steps:

1. Localhost credentials to be used are missing. 
![localhost](https://user-images.githubusercontent.com/72307234/158028299-b7292688-4ddd-40f2-bac3-ad81dddbfd02.PNG)

**Comment by bpmoring** [comment]
Thank you, we will look into this.

**Comment by VitalyMCT** [comment]
Yes, there is a missing step in the instructions here. It should ask students to use appropriate credentials, if the authentication dialog appears.

The reason the authentication dialog does not appear on the ALH VM is that someone (either course creator during their run through the lab, or the ALHs themselves), have already used that connection before. Since the connection was already used the credentials are now cached in the base VM images and PBI Desktop skips the prompt.

**Comment by Sharmajivibhor** [comment]
What credentials are to be used at this particular step ?

**Comment by bpmoring** [comment]
Instructions added for clarity.
