### ISSUE TITLE
LAB 10 review security role, is not reflecting Michael Blythe's info as requested

### ISSUE THREAD

**Issue by Yash-malhi** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#165]
#### **Which lab or demo?**
Lab Enforce Row-Level Security PL 300 github (12)

#### **Is your feature request related to a problem? Please describe.**
Task 2: Enforce row-level security (step 13 result is not what I get despite following the labs multiple times.)
![image](https://user-images.githubusercontent.com/88126448/218247142-48a074ba-e082-470e-bc1a-1d1b1e15432e.png)

#### **Describe the solution you'd like**
Expression userprincipalname is not returning with the user role suggested in the lab.

#### **Describe alternatives you've considered**
I tried creating a different role, replaced the reps name changed the filter. Please assist... Trainee is facing a lot of issues due to this.
#### **Additional context**

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by ed7257** [comment]
userprincipalname() function is used only when you publish to Power BI Service. Inside Power BI Desktop when you test you provide user's email and Power BI emulate a call of this function with entered by you email value. if this user exist in the table the table will get filtered only to the rows having that email value. You need to select the role you created and Other when testing. Also make sure you created role filter on the right table

**Comment by AngieRudduck** [comment]
@Yash-malhi  can you confirm the steps were followed exactly? I am able to reproduce the expected behavior following the instructions. 

- As @ed7257 stated, you need to select **both salesperson role that was just created AND select the other user to enter "michael-blythe@adventureworks.com".**
- Also make sure that you are on the correct table that you created the filter for. The lab instructs you to do it on Salesperson (Performance) but there is also a Salesperson table, which it doesn't work on without a filter.

![image](https://user-images.githubusercontent.com/34583336/220369745-32c5db68-2a13-4751-b72e-f1aa84d9e869.png)

**Comment by Yash-malhi** [comment]
Hey Angie,
The lab was practiced by my trainee while i observed.
Steps were exact... This has happened a couple of times in the past too
wherein the results aren't exact.

Hope this helps!

Regards,
Yash

**Comment by AngieRudduck** [comment]
@Yash-malhi Thanks for the additional information. Without seeing it firsthand, I can't say for certain what happened. I'm not able to reproduce it, and it's easy to miss one of the steps leading to wrong behavior.
