### ISSUE TITLE
Power BI lab 3 design data model Exercise 4: step 13-16

### ISSUE THREAD

**Issue by Yash-malhi** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#166]
In the instructions step 15 lab 3 Design data model image shows 22 million for Michael Blythe. however, making the relationship inactive does not show the salesperson's individual info is not reflected only the sales total is shown.

![Screenshot 2023-02-18 113955](https://user-images.githubusercontent.com/88126448/219844326-1ddb35c7-d5b1-4ad2-94ef-9715042bc846.png)

**Comment by AngieRudduck** [comment]
@Yash-malhi I'm able to reproduce this lab step. This is a very complicated process because first you are creating relationships with non-default settings, so a simple checkbox could affect your behavior. Your screenshot only shows the relationship, but I can't see that it didn't update the table. You can use the "Manage relationships" from the canvas to verify on the same page.

![image](https://user-images.githubusercontent.com/34583336/222464236-1ac29244-ca97-4c22-b293-6609694a575c.png)

![image](https://user-images.githubusercontent.com/34583336/222464331-4b6a714d-f1b0-436e-b4b9-a5706b60ea35.png)

**Comment by Yash-malhi** [comment]
Hey Angie,

Thank you for the response.

I'll try it again will keep you updated incase of concerns.

Thank you for getting back to me.

Regards,
Yash
