### ISSUE TITLE
[BUG] (Breaking/Non-breaking) (Short description)

### ISSUE THREAD

**Issue by Ellywati** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#177]
#### **Priority**
Identify if this is a **breaking** bug or not.

#### **Lab/Demo Number/Name**
Lab Load Data in Power BI Desktop

#### **Describe the bug**
On the Task 2: Configure the Salesperson query
Step 6 Select the SalesPersonFlag column header, then select the down-arrow, then FALSE, and click OK.

#### **Screenshots**
Add screenshots to help explain your problem.

#### **Expected behavior/Suggested Change**
Step 6 Select the SalesPersonFlag column header, then select the down-arrow, then TRUE, and click OK.

#### **Additional context**

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by Mihai-Ac** [comment]
Hello @Ellywati 

The steps are correct.
When first selecting the SalesPersonFlag filter, this shows up, with 3 options already selected (Select all, FALSE and TRUE).
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/110993710/fa93d6dc-0253-47d2-a8dc-0bda955779df)

The instructions indicate that one should select **FALSE**. Doing this will remove the check, leaving the filter with only one selection:  **TRUE**
![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/110993710/75c4775e-3117-4b63-be6e-b62d5ecab674)


In order to only have to select **TRUE**, one would need to first select **(Select all)** to remove all selections and then select **TRUE**
