### ISSUE TITLE
[BUG] (Non-breaking) (Create a Power BI Dashboard -> wrong file to publish)

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#184]
#### **Priority**
Low prio

#### **Lab/Demo Number/Name**
9 - [Create a Power BI Dashboard](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Instructions/09-create-power-bi-dashboard.md)

#### **Describe the bug**
- Lab takers have to open the D:\PL300\Labs\09-create-power-bi-dashboard\Starter file, and save it to D:\PL300\MySolution. In the next step, they have to publish it from the D:\PL300\Labs\09-create-power-bi-dashboard\Starter location. That doesn't make sense. 

#### **Expected behavior/Suggested Change**
From which location to publish correctly?

**Comment by weslbo** [comment]
Learners also got errors when trying to upload the 09 starter file. I think it is because the 09 starter .PBIX file is from an older version of Power BI, that is not compatible anymore with the latest version. They don't get the error when uploading the mysolution file (after saving in PBI Desktop)

<img width="786" alt="image" src="https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/53346841/6a3c3a9e-dc9e-47b4-9ee2-c1f70ee51b87">

**Comment by AngieRudduck** [comment]
Thanks @weslbo! I see the line item says to "save a copy [...] in MySolution", so it's not a *required* step, but I can see why it's confusing. I just removed it entirely, since they're really only working in the service for this lab.

For the second issue, I didn't have any issues opening it locally with a newer version or being prompted to upgrade. I'm also able to launch the starter file within the Skillable VM without issue. 

The only catch is that now it prompts me immediately to enter my email address, before Power BI Desktop fully loads, and it's not super intuitive because you either enter and *Continue* or *Cancel* and proceed without sign-in. 

![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/34583336/af869d06-70f3-4aee-8583-03318c630792)

It's a much longer process to enter email then, than it is to just click cancel. 

I can load the file both with or without signing in, so I'm not sure how to repro the user experience. If you have repro steps, let me know please! :)

**Comment by weslbo** [comment]
For the second issue, it’s about manually uploading the PBIX (older version saved) to PBI ServiceWesley De BolsterSent from my phoneOp 2 okt 2023 om 23:29 heeft Angie Rudduck ***@***.***> het volgende geschreven:﻿Re: [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst] [BUG] (Non-breaking) (Create a Power BI Dashboard -> wrong file to publish) (Issue #184)Thanks @weslbo! I see the line item says to "save a copy [...] in MySolution", so it's not a required step, but I can see why it's confusing. I just removed it entirely, since they're really only working in the service for this lab.For the second issue, I didn't have any issues opening it locally with a newer version or being prompted to upgrade. I'm also able to launch the starter file within the Skillable VM without issue.The only catch is that now it prompts me immediately to enter my email address, before Power BI Desktop fully loads, and it's not super intuitive because you either enter and Continue or Cancel and proceed without sign-in.It's a much longer process to enter email then, than it is to just click cancel.I can load the file both with or without signing in, so I'm not sure how to repro the user experience. If you have repro steps, let me know please! :)—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you were mentioned.Triage notifications on the go with GitHub Mobile for iOS or Android.
