### ISSUE TITLE
[Feature] (please improve the starter file for the dashboard)

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#185]
#### **Which lab or demo?**
Create a Power BI Dashboard

#### **Is your feature request related to a problem? Please describe.**
Learners are always confused how to pin visuals onto the dashboard. The problem is that in the original starter file, the visuals are too close to each other. Causing the pin icon to disappear

<img width="269" alt="image" src="https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/53346841/3a98c8d7-6807-4502-8949-33ef29b0f990">

#### **Describe the solution you'd like**
Please update the .pbix file so the visual have a bit more space in between them

**Comment by AngieRudduck** [comment]
Thanks again, @weslbo! Looking at this, the issue is the top visual, which I could see, but it overlapped almost perfectly with the other visual below. I moved them all down enough that there's space on top to have the context menu display above the graphic, which is the default behavior when there's sufficient space.

![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/34583336/2c71fcaf-cd34-47ad-a327-05992d38631f)
