### ISSUE TITLE
Unable to open Document - Current PBI Version incompatible

### ISSUE THREAD

**Issue by shielajchan** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#197]
#### Lab Exercise 09 - Create a Power BI dashboard
- https://learn.microsoft.com/en-us/training/modules/create-dashboards-power-bi/10-lab

#### **Describe the bug**
unable to use the labs because current version of the app is not updated. New version needs to be updated with administrator rights. 

#### **Screenshots**

![image](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/assets/72311300/d4d04b44-b2c1-4fdb-b8d0-ac5b54898a54)

#### **To Reproduce**
1. Open Lab 
2. Download Lab Files to D:\ Drive
3. Click 'Next Labs instruction'
4. Open Power BI Desktop
5. Navigate to the D:\PL300\Labs\09-create-power-bi-dashboard\Starter folder, and open the Sales Analysis file.

**Comment by AngieRudduck** [comment]
@shielajchan thank you for the repro steps. The issue was the instruction to open the PBIX. Since this exercise continues to have you upload the file from the service rather than publish from the Desktop app, those instructions were unnecessary and have now been removed. You should see it reflected, but if not, skip the steps 4-5 from your logged issue, and instead upload from the Power BI service, and let us know if you still have issues. Many thanks again.
