### ISSUE TITLE
Please revert to the older labs and instructions - were muuuch better

### ISSUE THREAD

**Issue by luconsta** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#225]
Hello Guys,

But after years of polishing the labs and finally get a final product that functions perfectly, you managed to break everyting and we have to start all over again.
I'm delivering this class for years but these new labs are harder to follow and understand.

Firstly, I don't like the new ideea to put starter and solution files in the same folder. Because now you have to rename the files everytime, while in the former labs you just copied the needed file over the one in My Solution folder and that's it... no more time lost.

Secondly, the labs are broken from the beginning where you instruct opening "01-Starter-Sales Analysis.pbix" file wile the images show the "older lab" "Sales Analysis" so this will create confusion on the students that will have the first contact with Power BI.

Also because of this strange decision of renaming files you broke the entire ideea of this class - to show the students how to work in the same file from the first lab to the last one - "Sales Analysis.pbix". The older labs were more closely to the real approach of working on a Power BI project - now the labs are broken into so individual steps that are no longer connected to each other... no continuity.

I'm very dissapointed on this new approach, and if there is any way to download the older set of labs (maybe there is an archive somewhere) maybe you could provide me the link to download and use the older instructions and older labs.

Unfortunately also the lab providers updated their VM's with these new instructions.

L.E.: At a second view... It seems much worse - in the older labs the "solution" file should be the "result of following the steps in the lab instructions" and the solution from a lab is the starter of the next one. Now again you break it from the first lab - the solution file contains "parameters"... that were never used in lab instructions there were just presented in a much later lab.

Did anyone bother try respect the instruction, exactly, from the first to the last lab and get the expected or presented results?

Kind Regards,
Lucian

**Comment by arnoldvilleneuve** [comment]
Say it isn't so, please! 
Arnold Villeneuve 613-833-0984 

    On Wednesday, July 31, 2024 at 03:06:45 a.m. EDT, luconsta ***@***.***> wrote:  
 
 


Hello Guys,

But after years of polishing the labs and finally get a final product that functions perfectly, you managed to break everyting and we have to start all over again.
I'm delivering this class for years but these new labs are harder to follow and understand.

Firstly, I don't like the new ideea to put starter and solution files in the same folder. Because now you have to rename the files everytime, while in the former labs you just copied the needed file over the one in My Solution folder and that's it... no more time lost.

Secondly, the labs are broken from the beginning where you instruct opening "01-Starter-Sales Analysis.pbix" file wile the images show the "older lab" "Sales Analysis" so this will create confusion on the students that will have the first contact with Power BI.

Also because of this strange decision of renaming files you broke the entire ideea of this class - to show the students how to work in the same file from the first lab to the last one - "Sales Analysis.pbix". The older labs were more closely to the real approach of working on a Power BI project - now the labs are broken into so individual steps that are no longer connected to each other... no continuity.

I'm very dissapointed on this new approach, and if there is any way to download the older set of labs (maybe there is an archive somewhere) maybe you could provide me the link to download and use the older instructions and older labs.

Unfortunately also the lab providers updated their VM's with these new instructions.

Kind Regards,
Lucian

**Comment by AngieRudduck** [comment]
@luconsta and @arnoldvilleneuve - thank you for your feedback. Our labs are used in multiple modalities and need to be modular to support all. I appreciate that the new experience will require some adjustment for instructors; however, we will not be reverting the changes or sustaining old versions of the labs. 

As an alternative, you can download the Allfiles.zip folder and have a similar experience with all labs in a single top-level folder.
