### ISSUE TITLE
Frequency of updates?

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#240]
No issue, but a question... How often do you schedule courseware and lab updates?  

Or, what triggers updating the labs to say the October version of Power BI?

Thanks

**Comment by AngieRudduck** [comment]
Thanks for the question, @microsmith! This repo is specific to learning exercises that are related to courses, but not exclusively. We aim for quarterly updates for the VM, which I assume you mean by "lab." Exercises and courseware are updated multiple times a year, but is not on a set schedule due to product changes, and so on. For courseware-related questions, the MCT Lounge is a better place for questions: https://aka.ms/mctcentral
