### ISSUE TITLE
Lab 8 alert notification

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#50]
# Module: 08
### Task: 
Exercise 1: Sales Monitoring dashboard screenshot
Exercise 3: Task 1 
#### Step: 5 (Verify that the Sales YTD tile displays an alert notification icon.)

Description of issue
The screenshot referred in Exercise 1 and the step 5 of Exercise 3, Task 1 are no longer valid as there is no tasks to set set the alert.

**Comment by luconsta** [comment]
Hello Microsoft,

It seems that it was more easier to delete de steps mentioned by @vipaiva to clean up this lab, instead of adding the required steps to "Configure a dashboard tile alert" :(

These steps were an interesting feature demonstration that was available in the original DA-100 class (https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/09-create-power-bi-dashboard.md#task-6-configure-an-alert) and I don't understand why eliminate this "one minute task"?

**Comment by bpmoring** [comment]
These steps are no longer included in the lab. It was removed because this is not a task identified for those completing the Microsoft Power BI Data Analyst certification.
